spring.application.name=order-service
server.port=8080
management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.payment-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.payment-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.payment-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.payment-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.payment-service.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.payment-service.permittedNumberOfCallsInHalfOpenState=3